### ISSUE TITLE
mean(AA,3) returns A (?)

### ISSUE THREAD

**Issue by mankoff** [grinsted/ImGRAFT#1]
Hi,

I'm looking into porting this to Octave. It mostly runs in the latest Octave compiled from source, and not so well in the latest release (4.0.0). In trying to get this to work in 4.0.0, I came across this line:

https://github.com/grinsted/ImGRAFT/blob/8ae18c7b5ceb73c36def1575e557ee0a563a234f/templatematch.m#L260

Which has the function call `mean(AA,3)`. I think that `AA` is only two dimensions, so I'm not sure what the effect of this call is. MATLAB docs https://www.mathworks.com/help/matlab/ref/mean.html state that `mean returns A when dim is greater than ndims(A) or when size(A,dim) is 1.`, which implies this call has no effect. Am I missing something here?

**Comment by grinsted** [comment]
That sounds great. The original idea is that it should also handle rgb images. But perhaps it would be better to just raise an error if ndims>2, since I don't have a better solution.
